apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 2
  selector:
    matchLabels:   
      si3mshady: node
      
  template:
    metadata:
      labels:        
        si3mshady: node
    spec:
      containers:
      - name: node
        image:  si3mshady/backend-map-dev:1
        ports:
        - containerPort: 8080
          hostPort: 8080

--- 
apiVersion: v1
kind: Service
metadata: 
  name: node
spec: 
  ports: 
    - port: 8080
      targetPort: 8080         
  selector: 
    si3mshady: node
  type: LoadBalancer
